-- MySQL Script generated by MySQL Workbench
-- Wed Mar  2 12:34:45 2022
-- Model: tarefas    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tarefas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tarefas` ;

-- -----------------------------------------------------
-- Schema tarefas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tarefas` DEFAULT CHARACTER SET utf8 ;
USE `tarefas` ;

-- -----------------------------------------------------
-- Table `tarefas`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tarefas`.`usuario` ;

CREATE TABLE IF NOT EXISTS `tarefas`.`usuario` (
  `id` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `papel` VARCHAR(50) NOT NULL DEFAULT 'usuario',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarefas`.`tarefa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tarefas`.`tarefa` ;

CREATE TABLE IF NOT EXISTS `tarefas`.`tarefa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `concluida` TINYINT(1) NOT NULL DEFAULT 0,
  `usuario_id` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarefa_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarefa_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tarefas`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
